x-judgedaemon-common-configuration: &judgedaemon-common-configuration
  image: domjudge/judgehost:8.3.1
  restart: on-failure:1
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
  privileged: true
  user: judgehost
  # depends_on:
  #   - domserver
  env_file:
    - judgehost.env

services:
  domserver:
    container_name: domserver
    image: domjudge/domserver:8.3.1
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup
      # - domserver_public_images:/opt/domjudge/domserver/webapp/public/images
      # - domserver_public_css:/opt/domjudge/domserver/webapp/public/css/custom
      # - domserver_public_js:/opt/domjudge/domserver/webapp/public/js/custom
      # - domserver_public_docs:/opt/domjudge/domserver/webapp/public/docs
    ports:
      - 12345:80
    depends_on:
      - mariadb
    env_file:
      - domserver.env
    restart: on-failure:3

  mariadb:
    container_name: mariadb
    image: mariadb:11.4.3-noble
    volumes:
      - mariadbdata:/var/lib/mysql
    ports:
      - "127.0.0.1:13306:3306"
    env_file:
      - domserver.env
    command: --max-connections=1000 
    #--innodb-log-file-size=2G --max-allowed-packet=1G --net_read_timeout=3600 --net_write_timeout=3600

  judgedaemon1:
    <<: *judgedaemon-common-configuration
    hostname: judgedaemon-0
    container_name: judgedaemon-0
    environment:
      DAEMON_ID: 0

  judgedaemon2:
    <<: *judgedaemon-common-configuration
    hostname: judgedaemon-1
    container_name: judgedaemon-1
    environment:
      DAEMON_ID: 1

volumes:
  mariadbdata:
  # domserver_public_images:
  # domserver_public_css:
  # domserver_public_js:
  # domserver_public_docs:




