services:
  domserver:
    container_name: domserver
    image: domjudge/domserver:8.3.1
    ports:
      - "127.0.0.1:12345:80"
    env_file:
      - domserver.env
    restart: "${DOCKER_RESTART_POLICY:-always}"
    volumes:
      - /opt/initial_admin_password.secret:/opt/domjudge/domserver/etc/initial_admin_password.secret
    depends_on: 
      mariadb:
        condition: service_healthy
        restart: true

  mariadb:
    container_name: mariadb
    image: mariadb:11.4.3-noble
    volumes:
      - mariadbdata:/var/lib/mysql
    ports:
      - "127.0.0.1:13306:3306"
    env_file:
      - domserver.env
    command: --max-connections=1000 --innodb-log-file-size=2G --max-allowed-packet=1G
    user: domjudge
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: "${DOCKER_RESTART_POLICY:-always}"

volumes:
  mariadb_data:
