services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASS}
      - MSSQL_PID=Express
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${MSSQL_PASS} -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  migrate:
    container_name: migrate
    build:
      context: .
      tags:
        - "${BACKEND_IMAGE_NAME}-build-stage"
      target: build
    entrypoint: ["./efbundle"]
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=${DATABASE_NAME};User Id=sa;Password=${MSSQL_PASS};TrustServerCertificate=True
    depends_on: 
      mssql:
        condition: service_healthy

  backend:
    container_name: backend
    image: ${BACKEND_IMAGE_NAME}
    build:
      context: .
      tags:
        - "${BACKEND_IMAGE_NAME}"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=${DATABASE_NAME};User Id=sa;Password=${MSSQL_PASS};TrustServerCertificate=True
    ports:
      - "127.0.0.1:8080:8080"
    depends_on: 
      mssql:
        condition: service_healthy
        restart: true
      migrate:
        condition: service_completed_successfully

volumes:
  mssqldata:
